import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andrei
 */
public class AdminContacte extends javax.swing.JFrame {

    /**
     * Creates new form AdminContacte
     */
   
    public AdminContacte() {
        initComponents();
        
        Agenda.fillStudentJtable();
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButtonMasculin);
        bg.add(jRadioButtonFeminin);
        
        ButtonGroup tf = new ButtonGroup();
        tf.add(jRadioButtonFix);
        tf.add(jRadioButtonMobil);
        
        jMenuItemDeschidere.setVisible(false);
        jMenuItemSalvare.setVisible(false);
        reclame();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser = new com.toedter.calendar.JDateChooser();
        jTextField_NrTf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonSterge = new javax.swing.JButton();
        jButtonAdauga1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Nume = new javax.swing.JTextField();
        jTextField_Prenume = new javax.swing.JTextField();
        jRadioButtonMasculin = new javax.swing.JRadioButton();
        jRadioButtonFeminin = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonEditeaza = new javax.swing.JButton();
        jTextField_Id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Filtrare = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButtonFix = new javax.swing.JRadioButton();
        jRadioButtonMobil = new javax.swing.JRadioButton();
        jComboBoxFiltrare = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButtonOrdonare = new javax.swing.JButton();
        jComboBoxOrdonare = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButtonFiltrare = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemDeschidere = new javax.swing.JMenuItem();
        jMenuItemSalvare = new javax.swing.JMenuItem();
        jMenuItemIesire = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField_NrTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NrTfActionPerformed(evt);
            }
        });
        jTextField_NrTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_NrTfKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel6.setText("Contacte");

        jButtonSterge.setText("Sterge");
        jButtonSterge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStergeActionPerformed(evt);
            }
        });

        jButtonAdauga1.setText("Adauga");
        jButtonAdauga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdauga1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nume:");

        jLabel2.setText("Prenume:");

        jLabel3.setText("Sex:");

        jLabel4.setText("Data Nasterii:");

        jLabel5.setText("Telefon:");

        jTextField_Nume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NumeActionPerformed(evt);
            }
        });

        jRadioButtonMasculin.setText("Masculin");
        jRadioButtonMasculin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMasculinActionPerformed(evt);
            }
        });

        jRadioButtonFeminin.setText("Feminin");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonEditeaza.setText("Editeaza");
        jButtonEditeaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditeazaActionPerformed(evt);
            }
        });

        jTextField_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IdActionPerformed(evt);
            }
        });

        jLabel7.setText("Id:");

        jTextField_Filtrare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FiltrareActionPerformed(evt);
            }
        });
        jTextField_Filtrare.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_FiltrareKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_FiltrareKeyTyped(evt);
            }
        });

        jLabel8.setText("Filtrare:");

        jLabel9.setText("Tip telefon:");

        jRadioButtonFix.setText("Fix");
        jRadioButtonFix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFixActionPerformed(evt);
            }
        });

        jRadioButtonMobil.setText("Mobil");
        jRadioButtonMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMobilActionPerformed(evt);
            }
        });

        jComboBoxFiltrare.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Numar fix", "Numar mobil", "Nascuti Astazi", "Nascuti LunaCurenta" }));
        jComboBoxFiltrare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFiltrareActionPerformed(evt);
            }
        });

        jLabel10.setText("Filtrare dupa:");

        jButtonOrdonare.setText("Ordonare");
        jButtonOrdonare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonOrdonareMouseReleased(evt);
            }
        });
        jButtonOrdonare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdonareActionPerformed(evt);
            }
        });

        jComboBoxOrdonare.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nume", "Prenume", "Data Nasterii", "Numar de telefon" }));
        jComboBoxOrdonare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOrdonareActionPerformed(evt);
            }
        });

        jLabel11.setText("Ordonare dupa:");

        jButton2.setText("x");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonFiltrare.setText("Filtrare");
        jButtonFiltrare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrareActionPerformed(evt);
            }
        });

        jButton3.setText("x");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jMenu1.setText("Fisier");

        jMenuItemDeschidere.setText("Deschidere");
        jMenuItemDeschidere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeschidereActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemDeschidere);

        jMenuItemSalvare.setText("Salvare");
        jMenuItemSalvare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalvareActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSalvare);

        jMenuItemIesire.setText("Iesire");
        jMenuItemIesire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIesireActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemIesire);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajutor");

        jMenuItem1.setText("Inregistrare");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Despre");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(37, 37, 37)
                                .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(37, 37, 37)
                                .addComponent(jRadioButtonMasculin)
                                .addGap(39, 39, 39)
                                .addComponent(jRadioButtonFeminin)
                                .addGap(35, 35, 35))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(37, 37, 37)
                                .addComponent(jTextField_Prenume, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel1))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Nume, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonSterge))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(jTextField_NrTf, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jButtonEditeaza)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonAdauga1))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel9)
                        .addGap(37, 37, 37)
                        .addComponent(jRadioButtonFix)
                        .addGap(30, 30, 30)
                        .addComponent(jRadioButtonMobil)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_Filtrare, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxOrdonare, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxFiltrare, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonFiltrare)
                                        .addGap(29, 29, 29)
                                        .addComponent(jButton2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonOrdonare)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3)))))
                        .addGap(30, 30, 30))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_Filtrare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_Nume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jComboBoxFiltrare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonFiltrare)
                            .addComponent(jButton2))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Prenume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonMasculin)
                            .addComponent(jLabel3)
                            .addComponent(jRadioButtonFeminin))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_NrTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButtonMobil)
                                .addComponent(jRadioButtonFix)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAdauga1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSterge, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEditeaza, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel11))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonOrdonare)
                                .addComponent(jComboBoxOrdonare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton3)))
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_NrTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NrTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NrTfActionPerformed

    private void jTextField_NrTfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NrTfKeyTyped
        // Allow only char

        if(!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_NrTfKeyTyped
    public void reclame() {
        int x = 0;
        showImage(x);
        Timer tm;
        tm = new Timer(1000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
               int x = (int)Math.floor(Math.random() * 5);
                showImage(x);
            }
        });
        add(jLabel12); 
        tm.start();
    }
        public void cautareCont () {
        ContactQuery cq = new ContactQuery();
        ArrayList<contactPrivate> cList = cq.cautareCnt(jTextField_Filtrare.getText());
        
        String[] colNames = {"Id","Nume", "Prenume", "DataNasterii", "Sex", "NumarDeTelefon", "TipTelefon" };
        Object[][] rows = new Object[cList.size()][7];
        
        for(int i=0; i<cList.size(); i++) {
                rows[i][0] = cList.get(i).getCid();
                rows[i][1] = cList.get(i).getFnume();
                rows[i][2] = cList.get(i).getLnume();
                rows[i][3] = cList.get(i).getBdate();
                rows[i][4] = cList.get(i).getSex();
                rows[i][5] = cList.get(i).getPhone();
                rows[i][6] = cList.get(i).getTipTel();
        }
        MyModel mmd = new MyModel(rows,colNames);
        AdminContacte.jTable1.setModel(mmd);
    }
    
    public void actualizareTabel() {
        jTable1.setModel(new DefaultTableModel(null, new Object[]{"Id", "Nume", "Prenume", "Sex", "DataNasterii", "Telefon", "TipTelefon"}));
        Agenda.fillStudentJtable();
    }
    private void jButtonStergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStergeActionPerformed
           int yesOrNo = JOptionPane.showConfirmDialog(null, "Doriti sa stergeti contactul selectat?","Stergeti contactul", JOptionPane.NO_OPTION);
           if(yesOrNo == 0) {
               int id = Integer.valueOf(jTextField_Id.getText());
               ContactQuery cq = new ContactQuery();
               cq.deleteContact(id);
               actualizareTabel();
               clearFields();
           }
           else if(jTextField_Id.getText().equals("")){
               JOptionPane.showMessageDialog(null, "No Student Selected");
           }
    }//GEN-LAST:event_jButtonStergeActionPerformed

    private void jButtonAdauga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdauga1ActionPerformed
          Agenda addcnt = new Agenda();
          addcnt.setVisible(true);
          addcnt.pack();
          addcnt.setLocationRelativeTo(null);
          addcnt.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonAdauga1ActionPerformed

    private void jTextField_NumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NumeActionPerformed
    
    public String[] getImg() 
    {
        File file = new File(getClass().getResource("Agenda/Images").getFile());
        String[] imagesList = file.list();
        return imagesList;
    };
     
    
    public void showImage(int index) {
        String[] imagesList = getImg();
        String imageName = imagesList[index];
        ImageIcon icon = new ImageIcon(getClass().getResource("Agenda/Images/"+imageName));
        Image image = icon.getImage().getScaledInstance(jLabel12.getWidth(),jLabel12.getHeight(), Image.SCALE_SMOOTH);
        jLabel12.setIcon(new ImageIcon(image));
    }
  
    

    
    public boolean verifNume() {
        Pattern p = Pattern.compile("[A-Za-z]{2,20}");
        Matcher m = p.matcher(jTextField_Nume.getText());
        if(!m.matches()) {
           JOptionPane.showMessageDialog(null, "Numele trebuie sa inceapa cu litera mare si sa fie fromat din mai mult de 2 litere");
           return false;
        } else {
        return true;
        }
    }
    public boolean verifNumar() {
        Pattern p = Pattern.compile("^[0-7][0-9]{9}$");
        Matcher m = p.matcher(jTextField_NrTf.getText());
        if(!m.matches()) {
           JOptionPane.showMessageDialog(null, "Numar de telefon Invalid");
           return false;
        } else {
        return true;
        }
    }
    
    public boolean verifDacaExista() {
         ContactQuery cq = new ContactQuery();
        List<contactPrivate> cList = cq.contactList();
        boolean contains = cList.contains(jTextField_Nume.getText()) && cList.contains(jTextField_Prenume.getText()) && cList.contains(jTextField_NrTf.getText()) ;
        JOptionPane.showMessageDialog(null, "Contactul exista deja");
        return false;
    }

    public boolean verifText(){
        if(jTextField_Nume.getText().equals("") || jTextField_Prenume.getText().equals("")
                || jTextField_Id.getText().equals("") || jTextField_NrTf.getText().equals("") || jDateChooser.getDate() == null)
        {
           JOptionPane.showMessageDialog(null, "Unul sau mai multe campuri sunt goale");
            return false;
        }
        else if(isSameDay(jDateChooser.getDate(),new Date())){
            JOptionPane.showMessageDialog(null, "Astazi este ziua dvs. La multi ani!!!");
            return true;
        }
        else if(jDateChooser.getDate().compareTo(new Date()) > 0){
            JOptionPane.showMessageDialog(null, "Data nasterii nu este valida!");
            return false;
        }
        return true;
    }
    
    private boolean isSameDay(Date date1, Date date2) {
    Calendar calendar1 = Calendar.getInstance();
    calendar1.setTime(jDateChooser.getDate());
    Calendar calendar2 = Calendar.getInstance();
    calendar2.setTime(date2);
    boolean sameYear = calendar1.get(Calendar.YEAR) == calendar2.get(Calendar.YEAR);
    boolean sameMonth = calendar1.get(Calendar.MONTH) == calendar2.get(Calendar.MONTH);
    boolean sameDay = calendar1.get(Calendar.DAY_OF_MONTH) == calendar2.get(Calendar.DAY_OF_MONTH);
    return sameDay && sameMonth;
    }
    public void clearFields () {
        jTextField_Id.setText("");
        jTextField_Nume.setText("");
        jTextField_Prenume.setText("");
        jTextField_Id.setText("");
        jTextField_NrTf.setText("");
        
    }
    
    private void jButtonEditeazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditeazaActionPerformed
        
        int id = Integer.valueOf(jTextField_Id.getText());
        String fnume = jTextField_Nume.getText();
        String lnume = jTextField_Prenume.getText();
        String phone = jTextField_NrTf.getText();
        String sex = "";
        if (jRadioButtonFeminin.isSelected()) {
            sex = "Feminin";
        } else if (jRadioButtonMasculin.isSelected()) {
            sex = "Masculin";
    }
        String tipTel = "";
        if (jRadioButtonMobil.isSelected()) {
            tipTel = "Mobil";
        } else if (jRadioButtonFix.isSelected()) {
            tipTel = "Fix";
        }

        if(verifText() && verifNumar() && verifNume() && verifDacaExista()){
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyy-MM-dd");
            String bdate = dateFormat.format(jDateChooser.getDate());
            contactPrivate cnt = new contactPrivate(id, fnume, lnume, bdate, sex, phone, tipTel);
            ContactQuery cq = new ContactQuery();
            cq.updateContact(cnt);
            actualizareTabel();
        }
    }//GEN-LAST:event_jButtonEditeazaActionPerformed

    private void jTextField_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IdActionPerformed

    private void jMenuItemDeschidereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeschidereActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filePath = f.toString();
        File file = new File(filePath);
        
//        try {
//            FileReader fr = new FileReader(file);
//            BufferedReader bf = new BufferedReader(fr);
//            jTable1.setModel(new DefaultTableModel(null, new Object[]{"Id", "Nume", "Prenume", "Sex", "DataNasterii", "Telefon", "TipTelefon"}));
//            Object[] rows = bf.lines().toArray();
//            
//            for(int i = 0; i<rows.length; i++) {
//                String[] columns = rows[i].toString().split("");
//                jTable1.addRow(rows);
//            }
//                  
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(AdminContacte.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jMenuItemDeschidereActionPerformed

    private void jMenuItemSalvareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalvareActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Salvare tabel");
        chooser.showSaveDialog(null);
        File f = chooser.getSelectedFile();
        String filePath = f.toString();
        File file = new File(filePath);
        
        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bf = new BufferedWriter(fw);
            
            for(int i=0; i<jTable1.getRowCount(); i++) {
                for(int j=0; j<jTable1.getColumnCount(); j++) {
                    bf.write(jTable1.getValueAt(i, j).toString()+" ");
                }
                bf.newLine();
            }
            bf.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(AdminContacte.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItemSalvareActionPerformed

    private void jMenuItemIesireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIesireActionPerformed
             exitProgram();
    }//GEN-LAST:event_jMenuItemIesireActionPerformed

      public void exitProgram()
  {
     int r= JOptionPane.showConfirmDialog(this,  
            "Doriti sa parasiti aplicatia?",
            "Iesire",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

     if ( r == JOptionPane.YES_OPTION)
            System.exit(0);
  } 
    private void jRadioButtonMasculinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMasculinActionPerformed
        
    }//GEN-LAST:event_jRadioButtonMasculinActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int rowIndex = jTable1.getSelectedRow();
        
        if(jTable1.getValueAt(rowIndex, 4).toString().equals("Masculin")) 
        {
            jRadioButtonMasculin.setSelected(true);
            jRadioButtonFeminin.setSelected(false);
        } else {
            jRadioButtonFeminin.setSelected(true);
            jRadioButtonMasculin.setSelected(false);
        }
        
        if(jTable1.getValueAt(rowIndex, 6).toString().equals("Mobil")) 
        {
            jRadioButtonMobil.setSelected(true);
            jRadioButtonFix.setSelected(false);
        } else {
            jRadioButtonFix.setSelected(true);
            jRadioButtonMobil.setSelected(false);
        }
        
        jTextField_Id.setText(jTable1.getValueAt(rowIndex, 0).toString());
        jTextField_Nume.setText(jTable1.getValueAt(rowIndex, 1).toString());
        jTextField_Prenume.setText(jTable1.getValueAt(rowIndex, 2).toString());
        jTextField_NrTf.setText(jTable1.getValueAt(rowIndex, 5).toString());
        
        Date bdate;
        try {
            bdate = new SimpleDateFormat("yyy-MM-dd").parse(jTable1.getValueAt(rowIndex, 3).toString());
            jDateChooser.setDate(bdate);
        } catch (ParseException ex) {
            Logger.getLogger(AdminContacte.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable1MouseClicked
    
            
    private void jTextField_FiltrareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FiltrareActionPerformed
        cautareCont();
        
    }//GEN-LAST:event_jTextField_FiltrareActionPerformed

    private void jTextField_FiltrareKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_FiltrareKeyTyped

    }//GEN-LAST:event_jTextField_FiltrareKeyTyped

    private void jTextField_FiltrareKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_FiltrareKeyPressed
        cautareCont();
     
    }//GEN-LAST:event_jTextField_FiltrareKeyPressed
   
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
               String cod = JOptionPane.showInputDialog(null, "Inroduceti codul pentru varianta full:" );
               String codCorect = "proiectJava";
         if(codCorect.equals(cod)) {
             JOptionPane.showMessageDialog(null, "Cod corect. Programul este in varianta full");
             jMenuItemDeschidere.setVisible(true);
             jMenuItemSalvare.setVisible(true);
             jLabel12.setVisible(false);
             
         }else{
            JOptionPane.showMessageDialog(null, "Cod incorect");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JOptionPane.showMessageDialog(null, "Autor: Rusu Andrei /n Despre Aplicatie: "
                + "Este o agenda telefonica, te ajuta sa tii evidenta persoanelor nascute in ziua si luna curenta.");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jRadioButtonMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMobilActionPerformed

    private void jRadioButtonFixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFixActionPerformed

    private void jComboBoxFiltrareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFiltrareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFiltrareActionPerformed

    private void jButtonOrdonareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdonareActionPerformed
            if(jComboBoxOrdonare.getSelectedItem().equals("Nume")) {
                SortandFilter.ordonareNume();
            }
            else if (jComboBoxOrdonare.getSelectedItem().equals("Prenume")) {
                SortandFilter.ordonarePrenume();
            }
            else if (jComboBoxOrdonare.getSelectedItem().equals("Data Nasterii")) {
                SortandFilter.ordonareData();
            }
            else if (jComboBoxOrdonare.getSelectedItem().equals("Numar de telefon")) {
                SortandFilter.ordonareNrTf();
            }
    }//GEN-LAST:event_jButtonOrdonareActionPerformed

    private void jComboBoxOrdonareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOrdonareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxOrdonareActionPerformed

    private void jButtonOrdonareMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOrdonareMouseReleased

    }//GEN-LAST:event_jButtonOrdonareMouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Agenda.fillStudentJtable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonFiltrareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrareActionPerformed
            if(jComboBoxFiltrare.getSelectedItem().equals("Numar fix")) {
                SortandFilter.filtrareNrFix();
            }
            else if (jComboBoxFiltrare.getSelectedItem().equals("Numar mobil")) {
                SortandFilter.filtrareNrMobil();
            }
            else if (jComboBoxFiltrare.getSelectedItem().equals("Nascuti LunaCurenta")) {
                SortandFilter.filtrareLunaCurenta();
            }
             else if (jComboBoxFiltrare.getSelectedItem().equals("Nascuti Astazi")) {
                SortandFilter.filtrareZiCurenta();
            }
    }//GEN-LAST:event_jButtonFiltrareActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Agenda.fillStudentJtable();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminContacte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminContacte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminContacte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminContacte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminContacte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAdauga1;
    private javax.swing.JButton jButtonEditeaza;
    private javax.swing.JButton jButtonFiltrare;
    private javax.swing.JButton jButtonOrdonare;
    private javax.swing.JButton jButtonSterge;
    private javax.swing.JComboBox jComboBoxFiltrare;
    private javax.swing.JComboBox jComboBoxOrdonare;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemDeschidere;
    private javax.swing.JMenuItem jMenuItemIesire;
    private javax.swing.JMenuItem jMenuItemSalvare;
    private javax.swing.JRadioButton jRadioButtonFeminin;
    private javax.swing.JRadioButton jRadioButtonFix;
    private javax.swing.JRadioButton jRadioButtonMasculin;
    private javax.swing.JRadioButton jRadioButtonMobil;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_Filtrare;
    private javax.swing.JTextField jTextField_Id;
    private javax.swing.JTextField jTextField_NrTf;
    private javax.swing.JTextField jTextField_Nume;
    private javax.swing.JTextField jTextField_Prenume;
    // End of variables declaration//GEN-END:variables
}
