import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andrei
 */
public class  Agenda extends javax.swing.JFrame {

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButtonMasculin);
        bg.add(jRadioButtonFeminin);
   
        jRadioButtonMasculin.setSelected(true);
        
        ButtonGroup tf = new ButtonGroup();
        tf.add(jRadioButtonFix);
        tf.add(jRadioButtonMobil);
        
        jRadioButtonFix.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Nume = new javax.swing.JTextField();
        jTextField_Prenume = new javax.swing.JTextField();
        jRadioButtonMasculin = new javax.swing.JRadioButton();
        jRadioButtonFeminin = new javax.swing.JRadioButton();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jTextField_NrTf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonAnuleaza = new javax.swing.JButton();
        jButtonAdauga1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioButtonFix = new javax.swing.JRadioButton();
        jRadioButtonMobil = new javax.swing.JRadioButton();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nume:");

        jLabel2.setText("Prenume:");

        jLabel3.setText("Sex:");

        jLabel4.setText("Data Nasterii:");

        jLabel5.setText("Nr telefon:");

        jTextField_Nume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NumeActionPerformed(evt);
            }
        });

        jRadioButtonMasculin.setText("Masculin");
        jRadioButtonMasculin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMasculinActionPerformed(evt);
            }
        });

        jRadioButtonFeminin.setText("Feminin");
        jRadioButtonFeminin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFemininActionPerformed(evt);
            }
        });

        jTextField_NrTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NrTfActionPerformed(evt);
            }
        });
        jTextField_NrTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_NrTfKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Contact Nou");

        jButtonAnuleaza.setText("Anuleaza");
        jButtonAnuleaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnuleazaActionPerformed(evt);
            }
        });

        jButtonAdauga1.setText("Adauga");
        jButtonAdauga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdauga1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Tip telefon:");

        jRadioButtonFix.setText("Fix");

        jRadioButtonMobil.setText("Mobil");
        jRadioButtonMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMobilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(41, 41, 41)
                        .addComponent(jRadioButtonFix)
                        .addGap(30, 30, 30)
                        .addComponent(jRadioButtonMobil)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAnuleaza)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonAdauga1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_NrTf, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jRadioButtonMasculin)
                                    .addGap(30, 30, 30)
                                    .addComponent(jRadioButtonFeminin))
                                .addComponent(jTextField_Prenume, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_Nume, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))
                        .addContainerGap(59, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_Nume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Prenume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButtonFeminin)
                    .addComponent(jRadioButtonMasculin))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_NrTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonMobil)
                        .addComponent(jRadioButtonFix)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnuleaza, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdauga1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_NumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NumeActionPerformed

    private void jButtonAnuleazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnuleazaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonAnuleazaActionPerformed
    public static void fillStudentJtable () {
        ContactQuery cq = new ContactQuery();
        ArrayList<contactPrivate> cList = cq.contactList();
        
        String[] colNames = {"Id","Nume", "Prenume", "DataNasterii", "Sex", "NumarDeTelefon", "TipTelefon" };
        Object[][] rows = new Object[cList.size()][7];
        
        for(int i=0; i<cList.size(); i++) {
                rows[i][0] = cList.get(i).getCid();
                rows[i][1] = cList.get(i).getFnume();
                rows[i][2] = cList.get(i).getLnume();
                rows[i][3] = cList.get(i).getBdate();
                rows[i][4] = cList.get(i).getSex();
                rows[i][5] = cList.get(i).getPhone();
                rows[i][6] = cList.get(i).getTipTel();
        }
           
        
        MyModel mmd = new MyModel(rows,colNames);
        AdminContacte.jTable1.setModel(mmd);
    }
    
    public boolean verifNumar() {
        Pattern p = Pattern.compile("^[0-7][0-9]{9}$");
        Matcher m = p.matcher(jTextField_NrTf.getText());
        if(!m.matches()) {
           JOptionPane.showMessageDialog(null, "Numar de telefon Invalid");
           return false;
        } else {
        return true;
        }
    }
        public boolean verifNume() {
        Pattern p = Pattern.compile("[A-Za-z]{2,20}");
        Matcher m = p.matcher(jTextField_Nume.getText());
        if(!m.matches()) {
           JOptionPane.showMessageDialog(null, "Numele trebuie sa inceapa cu litera mare si sa fie fromat din mai mult de 2 litere");
           return false;
        } else {
        return true;
        }
    }
    public boolean verifText(){
        
        if(jTextField_Nume.getText().equals("") || jTextField_Prenume.getText().equals("") 
               || jTextField_NrTf.getText().equals("") || jDateChooser.getDate() == null)
        {
           JOptionPane.showMessageDialog(null, "Unul sau mai multe campuri sunt goale");
            return false;
        }
        
        else if(isSameDay(jDateChooser.getDate(),new Date())){
            JOptionPane.showMessageDialog(null, "Astazi este ziua dvs. La multi ani!!!");
            return true;
        }
        else if(jDateChooser.getDate().compareTo(new Date()) > 0){
            JOptionPane.showMessageDialog(null, "Introduce o data de nastere corecta");
            return false;
        }
        else {
            return true;
        }
    }
    
     private boolean isSameDay(Date date1, Date date2) {
    Calendar calendar1 = Calendar.getInstance();
    calendar1.setTime(jDateChooser.getDate());
    Calendar calendar2 = Calendar.getInstance();
    calendar2.setTime(date2);
    boolean sameYear = calendar1.get(Calendar.YEAR) == calendar2.get(Calendar.YEAR);
    boolean sameMonth = calendar1.get(Calendar.MONTH) == calendar2.get(Calendar.MONTH);
    boolean sameDay = calendar1.get(Calendar.DAY_OF_MONTH) == calendar2.get(Calendar.DAY_OF_MONTH);
    return sameDay && sameMonth;
    }
    
     public boolean verifDacaExista() {
        ContactQuery cq = new ContactQuery();
        List<contactPrivate> cList = cq.contactList();
        boolean contains = cList.contains(jTextField_Nume.getText()) && cList.contains(jTextField_Prenume.getText()) && cList.contains(jTextField_NrTf.getText()) ;
        JOptionPane.showMessageDialog(null, "Contactul exista deja");
        return false;
    }
     
    public void refreshTable() {
        AdminContacte.jTable1.setModel(new DefaultTableModel(null, new Object[]{"Id", "Nume", "Prenume", "Sex", "DataNasterii", "Telefon", "TipTelefon"}));
        fillStudentJtable();
    }
    private void jButtonAdauga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdauga1ActionPerformed
        String fnume = jTextField_Nume.getText();
        String lnume = jTextField_Prenume.getText();
        String phone = jTextField_NrTf.getText();
        String tipTel = "Fix";
        if (jRadioButtonMobil.isSelected()) {
            tipTel = "Mobil";
        }
        String sex = "Masculin";
        if (jRadioButtonFeminin.isSelected()) {
            sex = "Feminin";
        }
        
        
        
        if(verifText() && verifNumar() && verifNume() && verifDacaExista()){
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyy-MM-dd");
        String bdate = dateFormat.format(jDateChooser.getDate());
        contactPrivate cnt = new contactPrivate(null, fnume, lnume, bdate, sex, phone, tipTel);
        ContactQuery cq = new ContactQuery();
        cq.insertContact(cnt);
        refreshTable();
        }
    }//GEN-LAST:event_jButtonAdauga1ActionPerformed

    private void jTextField_NrTfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NrTfKeyTyped
        // Allow only char
        if(!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_NrTfKeyTyped

    private void jTextField_NrTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NrTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NrTfActionPerformed

    private void jRadioButtonMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMobilActionPerformed

    private void jRadioButtonFemininActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFemininActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFemininActionPerformed

    private void jRadioButtonMasculinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMasculinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMasculinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdauga1;
    private javax.swing.JButton jButtonAnuleaza;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JRadioButton jRadioButtonFeminin;
    private javax.swing.JRadioButton jRadioButtonFix;
    private javax.swing.JRadioButton jRadioButtonMasculin;
    private javax.swing.JRadioButton jRadioButtonMobil;
    private javax.swing.JTextField jTextField_NrTf;
    private javax.swing.JTextField jTextField_Nume;
    private javax.swing.JTextField jTextField_Prenume;
    // End of variables declaration//GEN-END:variables
}
